export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_TO_CART";
export const INCREMENT_COUNT_OF_PRODUCT = "INCREMENT_COUNT_OF_PRODUCT";
export const DECREMENT_COUNT_OF_PRODUCT = "DECREMENT_COUNT_OF_PRODUCT";
export const CHANGE_SIZE_OF_PIZZA ="CHANGE_SIZE_OF_PIZZA";
export const CHANGE_SIZE_OF_LEMONADE ="CHANGE_SIZE_OF_LEMONADE";
export const CHANGE_SIZE_OF_COFFEE ="CHANGE_SIZE_OF_COFFEE";
