export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_TO_CART";
export const CHANGE_INCREMENT_COUNT_OF_PRODUCT = "CHANGE_INCREMENT_COUNT_OF_PRODUCT";
export const CHANGE_DECREMENT_COUNT_OF_PRODUCT = "CHANGE_DECREMENT_COUNT_OF_PRODUCT";
export const CHANGE_SIZE_OF_PIZZA ="CHANGE_SIZE_OF_PIZZA";
export const CHANGE_SIZE_OF_LEMONADE ="CHANGE_SIZE_OF_LEMONADE";
export const CHANGE_SIZE_OF_COFFEE ="CHANGE_SIZE_OF_COFFEE";
export const CHANGE_SIZE_FROM_CART ="CHANGE_SIZE_FROM_CART";
